version: '3.7'

services:

  # app:
  #   build: ./backend
  #   container_name: app
  #   command: npm start
  #   volumes:
  #     - ./backend:/usr/src/app
  #   ports:
  #     - 4000:4000

  # mongo:
  #   image: mongo:4.2.6
  #   restart: always
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data/db:/data/db